<h3><b>Introduction to Data Analytics - Exercise set 1 - Python and NumPy Basics</b></h3>

Put all your exercises (Jupyter Notebooks or Python-files) in your course Git-project.
Use either code comments or Jupyter Notebook markdown (text) to document which exercise you are doing and what a certain code section does! 
You can return all of these exercises in a single Jupyter Notebook, if you wish.

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/numpylogo.png" width="250"/>

<b>NOTE!</b> For each subtask, save the result into a separate variable!

In [3]:
# setup all needed modules and configurations
import numpy as np

# re-style the NumPy arrays
# remember to install needed module first:
# pip3 install numpy-html
%load_ext numpy_html

Run the cell below to enable custom style for NumPy arrays:

In [131]:
%%html
<style>
table {margin-top: 16pt;}
td {font-family: Arial, Helvetica, sans-serif !important; font-weight: 600; white-space: normal !important;}
tr:nth-child(even) {background: #b0d9eb !important; color: black}
tr:nth-child(odd) {background: #8fb1bf !important; color: black}
</style>

<h4><b>1. Create these lists without NumPy:</b></h4>

- List of 15 ones

- List of 15 number 7's

- List of numbers from 100 to 150

- List of even numbers between 0 and 100

- List of years that are divisible by 4 between 1950 and 2020

<br>

<b>Tip: creating a list with Python code is usually something like this:</b>

<pre>
numbers = []

for x in range(0, 5):
    numbers.append(x)
</pre>

In [132]:
# exercise 1.1, create lists without NumPy
# use additional code cells or different variable names for each subtask
ones = []
for x in range(0, 15):
	ones.append(1)
	
ones

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [133]:
sevens = []
for x in range(0, 15):
	sevens.append(7)
	
sevens

[7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7]

In [134]:
high_numbers = []
for x in range(100, 151):
	high_numbers.append(x)
	
high_numbers

[100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150]

In [135]:
even_numbers = []
for x in range(0, 101):
	if x % 2 == 0:
		even_numbers.append(x)

even_numbers

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100]

In [136]:
years = []
for x in range(1950, 2021):
	if x % 4 == 0:
		years.append(x)

years

[1952,
 1956,
 1960,
 1964,
 1968,
 1972,
 1976,
 1980,
 1984,
 1988,
 1992,
 1996,
 2000,
 2004,
 2008,
 2012,
 2016,
 2020]

<h4><b>2.	Now, create these arrays with NumPy!</b></h4>

- Array of 15 zeroes

- Array of 15 ones

- Array of 15 number 7's

- Array of numbers from 100 to 150

- Array of numbers from 1900 to 2021

- Array of even numbers between 0 and 100

- Array of years that are divisible by 4 between 1950 and 2020



In [137]:
# exercise 1.2, create lists WITH NumPy
# use additional code cells or different variable names for each subtask
import numpy as np

zeros = np.zeros(15).astype(int)
zeros

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [138]:
ones = np.ones(15).astype(int)
ones

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [139]:
sevens = np.ones(15).astype(int) * 7
sevens

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

In [140]:
numbers = np.arange(100, 151)
numbers

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150])

In [141]:
high_numbers = np.arange(1900, 2022)
high_numbers

array([1900, 1901, 1902, 1903, 1904, 1905, 1906, 1907, 1908, 1909, 1910,
       1911, 1912, 1913, 1914, 1915, 1916, 1917, 1918, 1919, 1920, 1921,
       1922, 1923, 1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932,
       1933, 1934, 1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942, 1943,
       1944, 1945, 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954,
       1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965,
       1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976,
       1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987,
       1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998,
       1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009,
       2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020,
       2021])

In [142]:
even_numbers = np.arange(0, 101, 2)
even_numbers

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [32]:
years = np.arange(1950, 2021)
years = years[years % 4 == 0]
years

array([1952, 1956, 1960, 1964, 1968, 1972, 1976, 1980, 1984, 1988, 1992,
       1996, 2000, 2004, 2008, 2012, 2016, 2020])

<h4><b style="color: red">Note: compare the NumPy code to the plain Python code after doing the exercises. Easier or more difficult? :) 
(answer in code comments or as text in Jupyter Notebook)</b></h4>

<h3>Numpy is easier&#128077;</h3>
<p>NumPy is easier and faster to use because it doesn't require initializing a list or using loops.</p>

<h3><b>3. Let's try out NumPy vectors and matrices:</b></h3>

- Create a NumPy vector (list) containing these values:<br>
<b><i>5, 16, 9, 2, 19, 18, 11, 7</i></b><br>
    - Use argmax() to find the position index of the largest value in the vector, and print it
<br><br>
- Create a 7x7 matrix, with values from 1 to 49

    - Extra task: Create this matrix (list of lists) without NumPy in Python!

<br>

- Generate 8x8 random number matrix, values between 0 and 5

- Generate 8x8 random number matrix, using standard normal distribution values (= values are between -3 and 3)


In [33]:
# exercise 1.3, NumPy vectors and matrices
# use different variable names for each subtask
# you can also make new code cells if you need
numbers = [5, 16, 9, 2, 19, 18, 11, 7]
data = np.array(numbers)
index = data.argmax()
print(f'index of largest value: {index}\n')

index of largest value: 4



In [34]:
seven_by_seven_matrix = np.arange(1, 50).reshape(7, 7)
seven_by_seven_matrix

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49]])

In [37]:
seven_list = []
seven_by_seven_list = []
for x in range(0, 7):
	for y in range(1, 8):
		seven_list.append((x * 7) + y)
		if y % 7 == 0:
			seven_by_seven_list.append(seven_list)
			seven_list = []
			break
print(f'7x7 list without NumPy:\n{seven_by_seven_list}\n')

7x7 list without NumPy:
[[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14], [15, 16, 17, 18, 19, 20, 21], [22, 23, 24, 25, 26, 27, 28], [29, 30, 31, 32, 33, 34, 35], [36, 37, 38, 39, 40, 41, 42], [43, 44, 45, 46, 47, 48, 49]]



In [38]:
random_matrix = np.random.rand(8, 8) * 5
random_matrix

array([[0.47572835, 1.1533889 , 2.57175693, 1.00769183, 0.57916176,
        4.2840731 , 1.62519198, 2.93152066],
       [0.68786077, 0.12300162, 4.22146657, 3.09244904, 3.51817182,
        2.52233029, 2.84060837, 3.20009204],
       [1.71859967, 0.51238   , 1.44763672, 0.2476773 , 4.33004549,
        0.75925343, 3.93431181, 2.55948941],
       [0.84653232, 4.22822028, 3.5158117 , 2.63308115, 4.29892384,
        2.31599682, 2.18794336, 0.53528548],
       [3.0503793 , 3.52932905, 3.86281038, 2.1139093 , 0.5825273 ,
        3.77674635, 0.9419459 , 0.86435552],
       [1.8386475 , 0.73370229, 2.78486823, 2.55852347, 1.00977822,
        0.28639019, 4.37438157, 1.88587229],
       [2.91905821, 0.62562186, 0.58289689, 0.54272111, 0.6706933 ,
        2.1038186 , 1.31302449, 4.26131162],
       [1.16334313, 3.64746845, 2.97311621, 1.70335994, 2.90806657,
        3.62609462, 2.37453878, 1.59622434]])

In [39]:
random_normal_matrix = np.random.randn(8, 8)
random_normal_matrix

array([[-0.20158127,  0.02032267,  0.56385129, -0.05232978, -0.89418627,
        -0.03431803, -0.17780299, -0.39968327],
       [-0.0315687 ,  0.14993976,  0.86037245, -0.01894885, -0.062318  ,
         0.31216655,  0.79986923,  0.3927366 ],
       [-1.49354654, -0.95940137, -0.33554779, -0.73348476, -1.18048443,
         1.15797151, -2.39321621, -0.82874913],
       [-1.17694375,  0.36902772, -1.14288911, -2.36683129, -0.23490948,
         1.60977249, -0.97279389,  0.39265319],
       [-1.87660215,  0.34596891, -2.11000777, -1.159887  , -0.02079607,
        -0.15779329, -0.94014266, -0.80940821],
       [-0.79728662, -0.40773955,  0.87302137,  0.77325607, -0.17595184,
        -1.02388149, -0.09022237, -0.51134699],
       [-0.00496984, -0.54879279, -0.49519033,  0.19077134, -1.85982156,
        -1.59181244, -0.01042226,  0.57447575],
       [ 0.87465971, -0.7506359 ,  0.2100467 ,  1.05733697,  0.78118064,
         1.76651607,  0.12364358, -1.24564678]])

<h3><b>4. Create a linearly spaced… </b></h3>

- array (list/vector) of 10 values between value 0 and 1

- 10x10 matrix between values 0 and 5

    - Extra task: create this matrix without NumPy as well!


<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/cubes.png"/>


In [40]:
# exercise 1.4, linspace
# use different variable names for each subtask
# you can also make new code cells if you need
linear_vector = np.linspace(0, 1, 10)
linear_vector

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [41]:
linear_matrix = np.linspace(0, 5, 100).reshape(10, 10)
linear_matrix

array([[0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
        0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545],
       [0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
        0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596],
       [1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
        1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646],
       [1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
        1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697],
       [2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
        2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747],
       [2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
        2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798],
       [3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
        3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848],
       [3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737374,
        3.78787879, 3.83838384, 3.88888889, 3.93939394, 3.98989899],
       [4.04040404, 4.09090909, 4.14141414, 4.19191919, 4.24242424,
        4.29292929, 4.34343434, 4.39393939, 4.44444444, 4.49494949],
       [4.54545455, 4.5959596 , 4.64646465, 4.6969697 , 4.74747475,
        4.7979798 , 4.84848485, 4.8989899 , 4.94949495, 5.        ]])

In [43]:
increment = 5 / 99
linear_list = []
linear_linear_list = []
for x in range(0, 10):
	for y in range(1, 11):
		linear_list.append(((x * 10) + y - 1) * increment)
		if y % 10 == 0:
			linear_linear_list.append(linear_list)
			linear_list = []
			break
print(f'linearly spaced 10x10 list without NumPy:\n{linear_linear_list}')

linearly spaced 10x10 list without NumPy:
[[0.0, 0.050505050505050504, 0.10101010101010101, 0.15151515151515152, 0.20202020202020202, 0.25252525252525254, 0.30303030303030304, 0.35353535353535354, 0.40404040404040403, 0.45454545454545453], [0.5050505050505051, 0.5555555555555556, 0.6060606060606061, 0.6565656565656566, 0.7070707070707071, 0.7575757575757576, 0.8080808080808081, 0.8585858585858586, 0.9090909090909091, 0.9595959595959596], [1.0101010101010102, 1.0606060606060606, 1.1111111111111112, 1.1616161616161615, 1.2121212121212122, 1.2626262626262625, 1.3131313131313131, 1.3636363636363635, 1.4141414141414141, 1.4646464646464645], [1.5151515151515151, 1.5656565656565655, 1.6161616161616161, 1.6666666666666667, 1.7171717171717171, 1.7676767676767677, 1.8181818181818181, 1.8686868686868687, 1.9191919191919191, 1.9696969696969697], [2.0202020202020203, 2.0707070707070705, 2.121212121212121, 2.1717171717171717, 2.2222222222222223, 2.2727272727272725, 2.323232323232323, 2.3737373737373

<h3><b>5. Recreate the matrices in code based on the pictures.</b></h3>

- Create this 3x5 matrix with NumPy:

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/matrix1.png"/>


Note: The values above have no logic, you'll have to feed basic Python lists to NumPy for this result


In [145]:
# exercise 1.5a, create matrix
numbers = [23, 34, 54, 31, 75]
data1 = np.array(numbers)
numbers = [33, 56, 78, 65, 97]
data2 = np.array(numbers)
numbers = [41, 32, 11, 39, 51]
data3 = np.array(numbers)
three_by_five = np.array([data1, data2, data3])
three_by_five

array([[23, 34, 54, 31, 75],
       [33, 56, 78, 65, 97],
       [41, 32, 11, 39, 51]])

- Generate this NumPy array:

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/matrix2.png" width="800"/>

In [146]:
# exercise 1.5b, generate NumPy array / matrix
eight_by_sixteen = np.arange(128, 256).reshape(8, 16)
eight_by_sixteen

array([[128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140,
        141, 142, 143],
       [144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
        157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172,
        173, 174, 175],
       [176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188,
        189, 190, 191],
       [192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204,
        205, 206, 207],
       [208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220,
        221, 222, 223],
       [224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236,
        237, 238, 239],
       [240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252,
        253, 254, 255]])

- Generate this NumPy array:

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/matrix3.png" width="500"/>

<b>Tips:</b> arange-function (and step-parameter) + reshape is recommended. Alternatively you can use broadcasting and division if you like.

In [47]:
# exercise 1.5c, generate NumPy array / matrix
ten_by_ten = np.arange(1, 101).reshape(10, 10) * 0.05
ten_by_ten

array([[0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ],
       [0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ],
       [1.05, 1.1 , 1.15, 1.2 , 1.25, 1.3 , 1.35, 1.4 , 1.45, 1.5 ],
       [1.55, 1.6 , 1.65, 1.7 , 1.75, 1.8 , 1.85, 1.9 , 1.95, 2.  ],
       [2.05, 2.1 , 2.15, 2.2 , 2.25, 2.3 , 2.35, 2.4 , 2.45, 2.5 ],
       [2.55, 2.6 , 2.65, 2.7 , 2.75, 2.8 , 2.85, 2.9 , 2.95, 3.  ],
       [3.05, 3.1 , 3.15, 3.2 , 3.25, 3.3 , 3.35, 3.4 , 3.45, 3.5 ],
       [3.55, 3.6 , 3.65, 3.7 , 3.75, 3.8 , 3.85, 3.9 , 3.95, 4.  ],
       [4.05, 4.1 , 4.15, 4.2 , 4.25, 4.3 , 4.35, 4.4 , 4.45, 4.5 ],
       [4.55, 4.6 , 4.65, 4.7 , 4.75, 4.8 , 4.85, 4.9 , 4.95, 5.  ]])

<h3><b>6. Use this matrix in your code:</b></h3>

dataset = np.arange(1, 37).reshape(6, 6)

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/matrix4.png"/>


In [147]:
# exercise 1.6a, matrix slicing
dataset = np.arange(1, 37).reshape(6, 6)
dataset

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

- Create a slice of the matrix that contains this part of the matrix:

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/matrix5.png"/>

In [148]:
# exercise 1.6b, matrix slicing
lower_right = dataset[3:, 2:]
lower_right

array([[21, 22, 23, 24],
       [27, 28, 29, 30],
       [33, 34, 35, 36]])

- Pick out this column slice from data

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/series1.png"/>

In [149]:
# exercise 1.6c, matrix slicing
column_slice = dataset[:4, 3:4]
column_slice

array([[ 4],
       [10],
       [16],
       [22]])

- Pick out this row from the data

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/series2.png"/>

In [150]:
# exercise 1.6d, matrix slicing
row_slice = dataset[2:3].transpose()
row_slice

array([[13],
       [14],
       [15],
       [16],
       [17],
       [18]])

- Pick out these three rows from data:

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/matrix6.png"/>

In [151]:
# exercise 1.6e, matrix slicing
lower_half = dataset[3:]
lower_half

array([[19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

<h3><b>7. Use this matrix:</b></h3>

<b>dataset_2 = np.arange(1, 50).reshape(7, 7)</b>

- Add 50 to all values in the array (use broadcasting)

- Get the sum of all values in the dataset

- Get sum of only odd numbers in the dataset

- Get the standard deviation of the values in the dataset

- Get the sum of all values by ROW in the dataset

- Get the sum of all values by COLUMN in the dataset (tip, use the axis –parameter)

<br>

- <b>Extra task:</b> Do the total sum, row sum and column sum exercises <u><b>without</b></u> NumPy in Python!

<br>
<b>Note:</b> Don't create a new dataset when adding 50 to all values in the array, use the existing one.
<br><br>
<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/desktopcomputer.png"/>


In [4]:
# exercise 1.7, NumPy -operations on a matrix
dataset_2 = np.arange(1, 50).reshape(7, 7)
dataset_2
# use different variable names for each subtask
# you can also make new code cells if you need

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49]])

In [5]:
dataset_2 = dataset_2 + 50
dataset_2

array([[51, 52, 53, 54, 55, 56, 57],
       [58, 59, 60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78],
       [79, 80, 81, 82, 83, 84, 85],
       [86, 87, 88, 89, 90, 91, 92],
       [93, 94, 95, 96, 97, 98, 99]])

In [6]:
dataset_sum = np.sum(dataset_2)
print(f'sum of dataset: {dataset_sum}')

sum of dataset: 3675


In [7]:
odd_sum = np.sum(dataset_2[dataset_2 % 2 == 1])
print(f'sum of odd values from dataset: {odd_sum}')

sum of odd values from dataset: 1875


In [8]:
deviation = np.std(dataset_2)
print(f'standard deviation of dataset: {deviation}')

standard deviation of dataset: 14.142135623730951


In [9]:
row_total = np.sum(dataset_2, axis=1)
row_total

array([378, 427, 476, 525, 574, 623, 672])

In [10]:
column_total = np.sum(dataset_2, axis=0)
column_total

array([504, 511, 518, 525, 532, 539, 546])

In [11]:
list_dataset = dataset_2.tolist()
list_total = 0
for nested_list in list_dataset:
	for x in nested_list:
		list_total += x
print(f'sum from list without NumPy: {list_total}')

sum from list without NumPy: 3675


In [12]:
list_row_total = []
for nested_list in list_dataset:
	total = 0
	for x in nested_list:
		total += x
	list_row_total.append(total)
print(f'sum by row from list without NumPy: {list_row_total}')


sum by row from list without NumPy: [378, 427, 476, 525, 574, 623, 672]


In [13]:
list_column_total = []
list_transposed_dataset = dataset_2.transpose().tolist()
for nested_list in list_transposed_dataset:
	total = 0
	for x in nested_list:
		total += x
	list_column_total.append(total)
print(f'sum by column from list without NumPy: {list_column_total}')

sum by column from list without NumPy: [504, 511, 518, 525, 532, 539, 546]


<br><br>
<h2><b>Advanced extra tasks for extra points (varying challenges, some require Googling):</b></h2>

<h3><b>1. Create two files for this exercise: save_matrix.py and read_matrix.py</b></h3>

- in save_matrix.py: create a 15x15 matrix, and save it to a file (matrix.txt)
 - in read_matrix.py, read matrix.txt, and convert it back to a NumPy matrix

NumPy has loadtxt() and savetxt()-functions for these purposes.


In [14]:
# advanced extra exercise 1
fifteen_by_fifteen = np.arange(1, 226).reshape(15, 15)

with open("matrix.txt", 'w') as f:
    np.savetxt(f, fifteen_by_fifteen, fmt='%d')
f.close()

In [15]:
with open("matrix.txt", 'r') as f:
    matrix = np.loadtxt(f, dtype=int)
f.close()
matrix

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15],
       [ 16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,
         29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,
         44,  45],
       [ 46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,
         59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,
         74,  75],
       [ 76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
         89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
        104, 105],
       [106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118,
        119, 120],
       [121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133,
        134, 135],
       [136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148,
        149, 150],
       [151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163,
        164, 165],
       [166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178,
        179, 180],
       [181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193,
        194, 195],
       [196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208,
        209, 210],
       [211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223,
        224, 225]])

<h3><b>2. Masked arrays are a feature of NumPy that allow us to deal with pieces data that are incorrect or missing in a dataset (for example, faulty measurements from equipment etc.).</b></h3>

Create a NumPy matrix, that contains numbers between 0 to 50, and put some faulty numbers in a 10 different spots 
(for example: -100)

Use a masked array to handle the -100 values in your matrix. Replace every -100 with 0.


In [1]:
# advanced extra exercise 2
import random

faulty_indexes = []
while True:
    rand = random.randint(0, 49)
    if rand not in faulty_indexes:
        faulty_indexes.append(rand)
    if len(faulty_indexes) >= 10:
        break
    
print(f'faulty indexes: {faulty_indexes}')

faulty indexes: [27, 45, 36, 24, 1, 40, 13, 5, 37, 9]


In [4]:
numbers = np.arange(1, 51)

for i in range(len(numbers)):
    if i in faulty_indexes:
        numbers[i] = -100

five_by_ten = numbers.reshape(10, 5)
print("faulty matrix:")
five_by_ten

faulty matrix:


array([[   1, -100,    3,    4,    5],
       [-100,    7,    8,    9, -100],
       [  11,   12,   13, -100,   15],
       [  16,   17,   18,   19,   20],
       [  21,   22,   23,   24, -100],
       [  26,   27, -100,   29,   30],
       [  31,   32,   33,   34,   35],
       [  36, -100, -100,   39,   40],
       [-100,   42,   43,   44,   45],
       [-100,   47,   48,   49,   50]])

In [5]:
# Create a masked array 
import numpy.ma as ma

masked_array = ma.masked_equal(five_by_ten, -100)
print('using masked array:')
masked_array

using masked array:


masked_array(
  data=[[1, --, 3, 4, 5],
        [--, 7, 8, 9, --],
        [11, 12, 13, --, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, --],
        [26, 27, --, 29, 30],
        [31, 32, 33, 34, 35],
        [36, --, --, 39, 40],
        [--, 42, 43, 44, 45],
        [--, 47, 48, 49, 50]],
  mask=[[False,  True, False, False, False],
        [ True, False, False, False,  True],
        [False, False, False,  True, False],
        [False, False, False, False, False],
        [False, False, False, False,  True],
        [False, False,  True, False, False],
        [False, False, False, False, False],
        [False,  True,  True, False, False],
        [ True, False, False, False, False],
        [ True, False, False, False, False]],
  fill_value=-100)

<h3><b>3. argsort is a feature of NumPy  that allows you to sort a NumPy array based on another NumPy array. </b></h3>

This is useful if you have two separate arrays, but their data  should be in sync even if order of data is changed. For example, one array contains the prices of cars, and another contains the manufacturing years. If we wish to sort the data by manufacturing years, and keep the prices in sync as well, argsort will be handy.

Useful link:
http://arogozhnikov.github.io/2015/09/29/NumpyTipsAndTricks1.html

Create two random datasets:

- Manufacturing years of 10 cars, values between 2010 and 2020

- Selling price of 10 cars, prices between 2000€ and 60000€

Use argsort to sort both datasets according to manufacturing years.


In [6]:
# advanced extra exercise 3
import numpy as np

years = np.random.randint(low=2010, high=2020, size=10)
prices = np.random.randint(low=2000, high=60000, size=10)

sorter = np.argsort(years)
print(f'sorted years: {years[sorter]}')
print(f'sorted prices: {prices[sorter]}')

sorted years: [2010 2013 2013 2013 2014 2015 2015 2015 2018 2019]
sorted prices: [29453 19942  2332 40321 22922 32403  9371 51737 24780 51886]


<h3><b>4. Try out the following additional NumPy features, and discuss in your code comments or in Jupyter Notebook text where they could be useful. You can also Google and search for ideas where these could be used. </b></h3>

You can write your thoughts as comments in the code or Jupyter text as you try out each feature.

- np.repeat()

- np.ravel()

- np.hsplit(), np.vsplit(), np.hstack, np.vstack()

- np.transpose()

- np.round()

- np.expand_dims(), np.squeeze()

- np.digitize()




In [8]:
# advanced extra exercise 4
# repeat repeats each element a number of times
arr = np.array([1, 2, 3])
repeated_arr = np.repeat(arr, 2)
repeated_arr

array([1, 1, 2, 2, 3, 3])

In [13]:
arr = np.array([1, 2, 3, 4]).reshape(2, 2)
arr

array([[1, 2],
       [3, 4]])

In [14]:
# ravel is the inverse of reshape
raveled_arr = np.ravel(arr)
raveled_arr

array([1, 2, 3, 4])

In [21]:
matrix_example = np.arange(1, 17).reshape(4, 4)
matrix_example

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [26]:
# hsplit splits the matrix into equal sizes column-wise
hsplit_result = np.hsplit(matrix_example, 2)
hsplit_result

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [34]:
# vsplit splits the matrix into equal sizes row-wise
vsplit_result = np.vsplit(matrix_example, 2)
vsplit_result

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [35]:
# hstack stacks columns together
# stacked back together in reverse order
hstack_result = np.hstack((hsplit_result[1], hsplit_result[0]))
hstack_result

array([[ 3,  4,  1,  2],
       [ 7,  8,  5,  6],
       [11, 12,  9, 10],
       [15, 16, 13, 14]])

In [36]:
# vstack stacks rows together
# stacked back together in reverse order
vstack_result = np.vstack((vsplit_result[1], vsplit_result[0]))
vstack_result

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [37]:
# Turns rows into columns (matrix transpose)
transposed_matrix = matrix_example.transpose()
transposed_matrix

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [147]:
# rounds all elements in array to specified number of decimal places
float_array = np.array([1.35, 1.44, 3.93, 4.55])
rounded_array = np.round(float_array, 1)
rounded_array

array([1.4, 1.4, 3.9, 4.6])

In [82]:
matrix_example.shape

(4, 4)

In [78]:
# expands the shape of an array
# it's like adding another dimension to the matrix
expanded_matrix = np.expand_dims(matrix_example, axis=1)
expanded_matrix.shape

(4, 1, 4)

In [79]:
# the inverse of expand_dims
squeezed_matrix = np.squeeze(expanded_matrix)
squeezed_matrix.shape

# expand_dims and squeeze are used to create a required shape for the matrix before conducting matrix operations

(4, 4)

In [151]:
# determines which bin each value in an array belongs to and returns the index of each corresponding bin
# bin is the closest lower number to the value
bins = np.array([1, 2, 3, 4])
indexes_lower = np.digitize(float_array, bins)
indexes_lower

array([1, 1, 3, 4], dtype=int64)